### ISSUE TITLE
I have a pull for this

### ISSUE THREAD

**Issue by kennebecstars** [futuretap/InAppSettingsKit-Swift-Sample#4]
I don't have permission to push this. How do we do this? Never did it before, to tell the truth. I originally did a git clone to get my start.

**Comment by futuretap** [comment]
Just fork the repository using the "Fork" button. Then push to your forked repo.
The GitHub website then should ask if you want to create a pull request. If it doesn't just reference your repository here and I can pull it from there.

**Comment by kennebecstars** [comment]
You should see this. I did this about a week ago, just poking around.

I swift, you have a basic issue: that the app cannot be named the same as the package it uses, so I had to change that. I did another version of the MainViewController.swift. I did a lot of updates from the one I found there (basically, coded it from what you had in objective-c, added a few enhancements for mail handling and some other stuff; but you’ll see that in the diffs.)

I just tried to learn something about InAppSettingsKit. I almost understand enough by now to get going to use it from Swift.

-Paul Crowell

**Comment by futuretap** [comment]
You seem to have forked the code from the main repo, not this one. So it's hard to see your actual changes. I'll have a look but it'll probably take some time (after WWDC) until I get to it.

**Comment by kennebecstars** [comment]
What I checked out was InAppSettingsKit-Swift-Sample-f5d4d6e9cd2f0ca5d4065f0ad5a719d6047a0ae6

That’s where I created the fork,

-pc
